### ISSUE TITLE
Error running id_estimate()

### ISSUE THREAD

**Issue by OyvindStiansen** [saudiwin/idealstan#13]
Hi, 

Running id_estimate() consistently returns the following error message: 
mingw32-make.exe: *** [make/program:14: src/cmdstan/main_threads_opencl.o] Error 1

Any suggestions for how to solve this error?

**Comment by saudiwin** [comment]
hmmm. what version are you using? the CRAN version?

**Comment by OyvindStiansen** [comment]
I am using idealstan_1.0 installed from github.

I am running R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

**Comment by saudiwin** [comment]
huh ok is this the master branch?

**Comment by saudiwin** [comment]
I think I accidentally. pushed the develop branch to the master branch, so you're using unstable code. If you want to use the package under construction, you can do remotes::install_github("saudiwin/idealstan", ref="develop")

**Comment by saudiwin** [comment]
Note that the documentation is out of date and you'll need to install cmdstanr first. I won't be updating documentation until later this summer.

**Comment by OyvindStiansen** [comment]
Thanks! I reinstalled the package now, using the develop version. However, I still get the same error when running id_estimate(). I have cmdstanr installed.

**Comment by jpredist** [comment]
same error as this

**Comment by jpredist** [comment]
this isn't a cmdstanr problem to my knowledge -- running `cmdstanr::cmdstanr_example()` works

**Comment by saudiwin** [comment]
Hi @OyvindStiansen @jpredist -- it's great to hear you all are using the develop/unstable branch! It is largely feature-complete but not documented yet (anticipate a release later this summer). I develop on the Mac OS so that's why I didn't come across this before.

I believe what is happening here is related to OpenCL support on Windows. One of the Stan files that is compiled in the new version includes OpenCL. That's why the cmdstanr example program will compile fine, but this one won't. 

I don't have any specific "fixes" for this at the moment as I haven't gotten to the stage of doing cross-platform checks (though will soon), although if you can get OpenCL installed on your machine that works with `cmdstan`, that should do the trick. On the other hand, if you want to debug/fix the package yourself, feel to fork and then comment out lines in the `id_estimate` function that compile an `irt_standard_gpu.stan` file. That will prevent the package from compiling this particular Stan file, and it should otherwise work fine as long as the `GPU` option is set to FALSE. The GPU support in any case doesn't appear to do much for estimation, so if this turns out to be an insurmountable issue on Windows I may simply disable it.

**Comment by bshor** [comment]
One option in the meantime for Windows users is to try it in Linux with WSL2, which provides a pretty seamless and easy way to run Linux inside Windows.

**Comment by saudiwin** [comment]
good to know, thanks @bshor !

**Comment by sophiaschlosser** [comment]
I have a similar error with the id_estimate function, not sure if it is exactly the same though:
```


0  0x10e2701cc  __assert_rtn + 123
1  0x10e2753db  ld::tool::OutputFile::addressAndTarget(ld::Internal const&, ld::Fixup const*, ld::Atom const**) (.cold.1) + 0

2  0x10e1b5209  ld::tool::OutputFile::addressOf(ld::Internal const&, ld::Fixup const*, ld::Atom const**) + 309
3  0x10e1b671c  ld::tool::OutputFile::applyFixUps(ld::Internal&, unsigned long long, ld::Atom const*, unsigned char*) + 2392

4  0x10e1bb911  ld::tool::OutputFile::writeAtoms(ld::Internal&, unsigned char*) + 351
5  0x10e1b288d  ld::tool::OutputFile::writeOutputFile(ld::Internal&) + 821
6  0x10e1a9e69  ld::tool::OutputFile::write(ld::Internal&) + 189

7  0x10e1286e3  main + 774
A linker snapshot was created at:
	/tmp/model-1719434c28852-2021-11-02-221010.ld-snapshot
ld: Assertion failed: (_mode == modeFinalAddress), function finalAddress, file /Library/Caches/com.apple.xbs/Sources/ld64/ld64-650.9/src/ld/ld.hpp, line 1161.

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [/var/folders/m8/w_9gggz16zv5klqbmxwrcsrh0000gn/T/RtmpHpackG/model-1719434c28852] Error 1

```

This error was consistent across R version 3.5, 3.63 and 4.12 with reinstalling the package from the master and develop branch. Im also on MacOS 11.6. 

The `cmdstanr::cmdstanr_example() `works without any error.

Thank you for your efforts in developing and maintaining this otherwise awesome project :)

**Comment by michalovadek** [comment]
I can also echo the installation and running issues. I recently tried installing various versions of the package on two different Windows machines, trying with both R 3.6.x and 4.1.x, but ultimately to no avail, despite `cmdstanr` working fine.

**Comment by saudiwin** [comment]
Hi guys - I'll try to post some updated code here in the next few days for how to use the new version of idealstan. The syntax has changed quite a bit but I believe I can share enough for you all to do your work with the package while I'm preparing for a full v1.0 release (!!).

**Comment by saudiwin** [comment]
The beta release for v1.0 has been published - see the README file in the master branch. That should get rid of these issues.
