### ISSUE TITLE
Select all that apply type questions

### ISSUE THREAD

**Issue by spinkney** [saudiwin/idealstan#4]
I'm opening another question, since it's only tangentially related to my previous issue, [Multivariate mixed response feature?](https://github.com/saudiwin/idealstan/issues/3).

Do the models allow one to estimate "select all that apply" type questions? There is a model in [DeSarbo and Cho](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2785857) that seems promising and a great Stan model. I can attempt to code one out and post for reference.

**Comment by saudiwin** [comment]
No I don't currently have a multinomial/categorical model yet. It's not so hard to include it, although I would note that in this case it's relatively easy to recode your data to use the existing binary/logit models by expanding the choice list to separate columns. So if you  have a survey response with categories {applies, bananas, watermelon}, simply make three columns that equal 1 if that option was selected and 0 otherwise. 

If that wouldn't work for your problem and there is another model that would do better, I'm open to looking at it.

**Comment by saudiwin** [comment]
I'm not really convinced I should implement this as it can just be converted to a series of 0/1 variables.
